### ISSUE TITLE
Objects which are mirrored around a pivot are not exported correctly

### ISSUE THREAD

**Issue by spawnie-no-oni** [EdyJ/blender-to-unity-fbx-exporter#1]
Project which causes the issue : https://gitlab.com/JoBarthel/wings
Steps to reproduce : 

- select the collection "uv'd wings" and export to Unity FBX, ticking "Active Collection Only".
- import the fbx file into unity. 

Expected result : 
![image](https://user-images.githubusercontent.com/58695361/83337074-c752dc80-a2b8-11ea-9a7b-8cb2615dd106.png)

Actual result : 

![image](https://user-images.githubusercontent.com/58695361/83337089-ddf93380-a2b8-11ea-95ff-92e18d30b078.png)

**Comment by EdyJ** [comment]
Fixed, thanks for the great repro scene
