### ISSUE TITLE
Exporting collection with Empties gives Runtime error

### ISSUE THREAD

**Issue by TedSwanseaUni** [EdyJ/blender-to-unity-fbx-exporter#11]
I'm not familiar with Blender but when testing this addon I noticed exporting collection that contains Empty objects results in a error:

Traceback (most recent call last):
  File "C:\Program Files\Blender Foundation\Blender 2.90\2.90\scripts\modules\bpy\ops.py", line 201, in __call__
    ret = op_call(self.idname_py(), None, kw)
RuntimeError: Operator bpy.ops.object.convert.poll() failed, context is incorrect

location: <unknown location>:-1

Just selecting the mesh objects and using Selected Objects Only works but the rotations are not correct.  Is there a way around this or is the solution just not to use empty objects? Thanks.

**Comment by EdyJ** [comment]
It should be fixed in this version, please try it and let me know if this works:
https://github.com/EdyJ/blender-to-unity-fbx-exporter/blob/dev/fix-armature/blender-to-unity-fbx-exporter.py

**Comment by TedSwanseaUni** [comment]
Yes that works, thanks Edy :)
