### ISSUE TITLE
Looping animations does not function

### ISSUE THREAD

**Issue by plufz** [EdyJ/blender-to-unity-fbx-exporter#16]
Hi!

When exporting a humanoid with bones and animations into unity and ticking the "loop time" checkbox in the unity import settings the animation will not loop for me (the animation still only plays once). The loop works when I make a standard exported fbx but it does not work when I use your script nor if I use the experimental "apply transform" setting when exporting a standard fbx. Is this a known issue? I really love your script and would so like to be able to fix this issue. Please say if you need example files from me.

**Comment by plufz** [comment]
Sorry, I'm closing this issue. It was my fault, I had multiple animations with the same name and I just missed which animation was playing. It works fine! Again love your script! Thanks!

**Comment by EdyJ** [comment]
Thank you! Glad to know that you've got it sorted.
