### ISSUE TITLE
Unable to export after deleting an object.

### ISSUE THREAD

**Issue by Davidnovarro** [EdyJ/blender-to-unity-fbx-exporter#17]
I've encountered an exception when trying to export the scene right after removing one of the objects.

How to reproduce:
**1)** Open an empty blender scene
**2)** In object mode add two Cube objects.
**3)** Remove one.
**4)** Try to export without selecting any object. (File > Export > Unity FBX)

Throws an exception **"context is incorrect"**.

Screenshot - https://i.imgur.com/teWwMKt.png
I'm using Blender version 2.90.1

**Comment by EdyJ** [comment]
Thank you for reporting. I've reproduced this issue also in 2.83.5. I'll take a good look at it.

**Comment by EdyJ** [comment]
BTW, the workaround is simply select some object before exporting.

**Comment by Davidnovarro** [comment]
> BTW, the workaround is simply select some object before exporting.
I knew it, I was struggling like 15 minutes until I accidentally selected an object and then tried to export :)

"4) Try to export **without selecting any object**. (File > Export > Unity FBX)"
