### ISSUE TITLE
Scaling issue with rigged character

### ISSUE THREAD

**Issue by sstrong2** [EdyJ/blender-to-unity-fbx-exporter#19]
I have a rigged character I'm trying to get published to asset store. When I export FBX the rig (I think) it is being scaled up by 100 so in Unity when character is animated, things don't go so well.

Without using this exporter, character moves correctly but rigging is -89.98 on X and scale is 100,100,100. All the body meshes have correct 1,1,1 scale.

My goal is to have it pass the "Fix Orientation" issue in the Unity Package Validator.

![image](https://user-images.githubusercontent.com/16025488/115984952-265dc600-a5dc-11eb-8e47-d55aa5689152.png)

Blender 2.91 with Unity 2018.4, have also tried with U2019.4 (similar result)

**Comment by EdyJ** [comment]
Could you provide some .blend file to reproduce the issue?

**Comment by sstrong2** [comment]
Do you have a private upload area or should I just email it to you? The file is 5.3 MB - its not for public consumption.

**Comment by EdyJ** [comment]
You could remove everything but a single object that shows the issue, also removing the meshes with cylinders or other primitives. That would also be much more convenient for finding the problem.

**Comment by EdyJ** [comment]
Closing this issue as no repro has been provided.
