### ISSUE TITLE
Not working with armature.

### ISSUE THREAD

**Issue by alexisstrat** [EdyJ/blender-to-unity-fbx-exporter#2]
Thank you for this tool! It does work on generic meshes but not in objects with armatures.
Attached is a simple scene with suzanne and a bone. The rotation still has to be -90 inside unity for a correct pose.
[suzanne.zip](https://github.com/EdyJ/blender-to-unity-fbx-exporter/files/4815762/suzanne.zip)

**Comment by EdyJ** [comment]
Thank you! Will take a good look at it.

**Comment by EdyJ** [comment]
I've fixed it for that bone, but could you update the example with a hierarchy of 3-4 bones depth? I want to ensure the rotations get fixed correctly along all the armature.
