### ISSUE TITLE
Rotation problem?

### ISSUE THREAD

**Issue by liunliun** [EdyJ/blender-to-unity-fbx-exporter#20]
![image](https://user-images.githubusercontent.com/40163509/116337265-6e632f80-a80c-11eb-847c-85e2eb6028bc.png)
here is the pic that face to -y in blender.
and when export to unity ,it will face to oppsite direction like this
![image](https://user-images.githubusercontent.com/40163509/116337349-8e92ee80-a80c-11eb-8895-87318dc0d87d.png)

**Comment by EdyJ** [comment]
It's working correctly. "Front" in Blender is -Y, while "Front" in Unity is +Z. The object is facing -Y in Blender and +Z in Unity, which is the expected behavior. Simply rotate your view in Unity so +Z point towards you.
