### ISSUE TITLE
Scaling parameter in export

### ISSUE THREAD

**Issue by ThesisNotIncluded** [EdyJ/blender-to-unity-fbx-exporter#22]
Please add scaling parameter like in basic fbx exporter D:

**Comment by EdyJ** [comment]
Thanks for your suggestion, but the goal of this project is to be as simple as possible, excluding any non-essential option. There are multiple possibilities already to specify a non-destructive scale in both Blender and Unity, so I don't think a scaling parameter would fit in this exporter.
