### ISSUE TITLE
Painted texture gets reset

### ISSUE THREAD

**Issue by ratkingsminion** [EdyJ/blender-to-unity-fbx-exporter#23]
I often forget to press Alt+S to save the current texture I'm painting. So it's very disheartening when the exporter just resets the texture to its currently saved state right after exporting.

**Comment by EdyJ** [comment]
Sorry, I'm not used to that feature. Can you please describe how to reproduce the issue step by step for someone that has never used that feature?

**Comment by ratkingsminion** [comment]
Some simple steps, based on the standard Blender cube scene.
1) Create an image by choosing the "UV Editing" layout and clicking on "+ New". Save the image via Alt+S in any directory.
2) Choose the "Texture Paint" layout, on the right set Mode to "Single Image" instead of "Material". For the image, choose the one you created. Paint a bit on it, save it via Alt+S.
3) Paint a bit more on it, but don't save.
4) Export the cube via Unity FBX exporter. The texture now is back to the state from step 2, all the changes from step 3 are gone without warning.
