### ISSUE TITLE
Enhancement: Choosing the final bone orientation standard

### ISSUE THREAD

**Issue by Julian-Druzdzel** [EdyJ/blender-to-unity-fbx-exporter#24]
Currently this great tool's resulting fbx bones all point 'upward' towards their proceeding bones.
It would be awesome if one could choose another orientation standard at export, such as 'forward'.

**Comment by EdyJ** [comment]
Thanks for the suggestion. Is there an equivalent option for this in the default FBX exporter?

**Comment by Julian-Druzdzel** [comment]
In Blender's default FBX exporter, you can open the 'Armature' tab and choose the Primary and Secondary bone axes.
