### ISSUE TITLE
Add-on doesn't install

### ISSUE THREAD

**Issue by rccDave** [EdyJ/blender-to-unity-fbx-exporter#29]
I tried two different downloads: One of only the .py file and a second of the whole .zip.
When the first did not install, I tried the second.
Edit > Pref > Addons > Install seemed to proceed normally, even with a message at the bottom saying it was loading.
I see no error message.  The Addon is not in the list.  Search for "fbx" only shows the default Blender FBX exporter.
Do I need to disable that one, perhaps?  Can they co-exist?
Am I doing something wrong?

**Comment by EdyJ** [comment]
In that case there should be some error in the output describing the reasons, check them out. Also, what's your Blender version?
Yes, both exporters can be installed and working at the same time.

**Comment by rccDave** [comment]
Thanks for the reply.

I tried the install again with the Blender console showing.  I saw nothing in the way of errors listed there.  After clicking "Install", a note in the lower right of the screen said "Loading <path and filename>".  After about 5 seconds, it vanished.  There were no signs of errors.  It all looked like a normal install.

I'm using Blender 3.3.0

**Comment by IGrobenskiTT** [comment]
Same here, I think it's something due to Blender version, I'm also on 3.3.0, on older versions it worked fine (2.9, etc.) , can you guys fix this?

**Comment by Andazeus** [comment]
It is not working for me as well. Blender version 3.41. Getting the following console output:
"Modules Installed () from 'C:\\Users\\User\\Downloads\\blender-to-unity-fbx-exporter.py' into 'C:\\Users\\User\\AppData\\Roaming\\Blender Foundation\\Blender\\3.4\\scripts\\addons'"

**Comment by Andazeus** [comment]
Never mind, I was just dumb. Don't try to download the file via right click from Github, make sure to get the raw file as it added some html nonsense to it otherwise. Maybe make a release file just containing the actual script for people to download to avoid this user error in the future?

**Comment by EdyJ** [comment]
Add-on tested and working in Blender 3.4.1
