### ISSUE TITLE
Instanced collection child has extra 90 degrees of rotation in Unity

### ISSUE THREAD

**Issue by Swahhillie** [EdyJ/blender-to-unity-fbx-exporter#3]
Hello,

I noticed that the children of an instanced collection get an unneeded 90 degrees rotation over the X-axis.
Clearing this childs rotation in unity gets me what I need.

[blender-to-unity-fbx-exporter-repro.zip](https://github.com/EdyJ/blender-to-unity-fbx-exporter/files/4858682/blender-to-unity-fbx-exporter-repro.zip)

**Comment by EdyJ** [comment]
I've checked this out and currently I can't see a clear way to fix it. It seems that the collection instances are exported as a new object in the hierarchy being the parent of the duplicated collection. 

Applying the rotation requires converting the instance to actual objects before modifying the matrices. I can do that in the editor with Object > Apply > Make Instances Real, but then the collection gameobject is removed and the content of the instanced collection is duplicated (adding .001 etc to the names) and copied to the root of the current collection. In that situation the fix would work, but the exported geometry would be different than using the default FBX exporter. 

I'm not sure on what to do. Maybe I could re-create the collection instance as Empty object, then make it the parent of the duplicated collection content. But again, the names would be different than those assigned with the default FBX exporter.

**Comment by EdyJ** [comment]
I can't find a way to solve this properly, so I'm closing this issue for now. It has been added as _known issue_ in the readme.

Feel free to comment if you can provide further information or suggestions on resolving the problem.
