### ISSUE TITLE
objects exports with wrong rotation

### ISSUE THREAD

**Issue by Mornedil** [EdyJ/blender-to-unity-fbx-exporter#30]
Object in blender at rotation 0,0,0 is facing -Y with +X to it's left.
When imported to unity, object at rotation 0,0,0 is facing +Z with -X to it's left. (rotation difference of 180 degrees on the up-axis)

The object in blender has position/rotation/scale all applied so they're at 0,0,0 for pos/rot and 1,1,1 for scale

**Comment by Mornedil** [comment]
There is a unity import setting that fixes this - **Bake Axis Conversion**. It's off by default, turning it on fixes orientation

**Comment by EdyJ** [comment]
Please include a minimal .blend file that can be used to reproduce the issue. Thank you!

**Comment by EdyJ** [comment]
This is intended. Blender defines the "front" direction as -Y, while Unity defines "front" as +Z. Therefore, in both cases the object is facing "front".

**Comment by EdyJ** [comment]
Theoretically, the option "Bake Axis Conversion" in Unity fixes the FBX so the default FBX exporter could be used instead of this. I haven't tested this option though.
