### ISSUE TITLE
Wrong Rotation when exported object has "Fake User" enabled.

### ISSUE THREAD

**Issue by Johnscaban** [EdyJ/blender-to-unity-fbx-exporter#32]
When exporting, my model had a +90 degree rotation on the X-axis, but in Unity, it was zeroed. After messing around, I found that the "Fake User" option was causing the problem. After disabling it, the rotation was fixed.

I don't know if this is intended or not, but just wanted to point it out. I also tried to reproduce it in a new file and it still happened.

I'm using Blender 3.3.1

**Comment by EdyJ** [comment]
Could you provide the precise steps for reproducing the issue from a new file?

**Comment by Johnscaban** [comment]
I just opened a new file, deleted the default objects, added the monkey and enabled "Fake User" in the mesh (its the shield icon).
