### ISSUE TITLE
Use a base fbx file to determine what settings to export the updated fbx file in blender.

### ISSUE THREAD

**Issue by AraHaan** [EdyJ/blender-to-unity-fbx-exporter#38]
I have a problem where I am working on an VRChat avatar that I just so happened to have downloaded and worked on some customizations to it to:
- Optimized it by merging some meshes (using Cats)
- Optimized the material slots to be more helpful by merging similar ones together and reusing them.
  - Example is black, boots, & (Hair, Hair 1, & Hair 2)
- Armatures:
  - Example is that when I do not want to use the blender provided armatures, but the unity ones due to DPS (Deep Penetration Bones) and I want to preserve them. Also it seems that blender adds extra end bones than what the unity ones add.

Due to the above, it would be great if I could then tell the exporter "Use the original fbx file that will be overwritten on export to provide the very options that I need for the export." Also simple mesh merging should not require armature changes?

**Comment by EdyJ** [comment]
> Due to the above, it would be great if I could then tell the exporter "Use the original fbx file that will be overwritten on export to provide the very options that I need for the export." Also simple mesh merging should not require armature changes?

Unfortunately, the exported FBX file doesn't store any of the options used during the export, so they cannot be recovered afterwards. Even if there were some way to store custom data in the exported FBX file, reading the file before exporting just to recover such data is way beyond the scope of this exporter.
