### ISSUE TITLE
Exported objects are too big.

### ISSUE THREAD

**Issue by AraHaan** [EdyJ/blender-to-unity-fbx-exporter#39]
It seems that the exported objects when placed at the scale of 100, 100, 100 explicitly on the mesh entry itself render too big in Unity after exported.

**Comment by AraHaan** [comment]
![image](https://github.com/EdyJ/blender-to-unity-fbx-exporter/assets/15173749/94ce75b3-7279-41d0-aa7d-8044f47349b8)
![image](https://github.com/EdyJ/blender-to-unity-fbx-exporter/assets/15173749/c9113e58-7a43-48b9-9ddb-736fc38eeb0f)

The above image shows the armature when at the target size that is intended, the 2nd image shows the actual size that is obtained.

**Comment by AraHaan** [comment]
Interesting it seems it also nukes the shape keys which is not good at all for vrchat.

**Comment by EdyJ** [comment]
Exported objects preserve the scale that was defined in Blender. Placing the exported objects at a different scale in Unity will simply apply that scale.

**Comment by EdyJ** [comment]
> Interesting it seems it also nukes the shape keys which is not good at all for vrchat.
Possibly related issues: #27 #40
