### ISSUE TITLE
Missing Materials?

### ISSUE THREAD

**Issue by JGameMaker92** [EdyJ/blender-to-unity-fbx-exporter#41]
Why aren't materials also being exported with this plugin?

**Comment by EdyJ** [comment]
Couldn't reproduce the issue. Materials are included in the exported FBX file. Note that this plugin internally calls Blender's FBX Exporter to write the FBX file, so try the standard FBX Exporter to check if there's any difference in the materials. 

If the problem persists, feel free to reopen the issue with the precise steps to reproduce the problem, including a .blend file I could use.
