### ISSUE TITLE
New Version doesn't even let me export in both 2.83 and 2.92 :|

### ISSUE THREAD

**Issue by KiwiFemboy** [EdyJ/blender-to-unity-fbx-exporter#45]
For some reason it just refuses to export the FBX

https://github.com/EdyJ/blender-to-unity-fbx-exporter/assets/135325586/27da50aa-fab3-42a7-bb3c-139a1370fc9f

**Comment by EdyJ** [comment]
Please check the console and the information panel for any error message. Thanks!

**Comment by EdyJ** [comment]
...and post the information here, please, so I could check possible causes of the issue on your side.

**Comment by EdyJ** [comment]
Can't reproduce. No further information provided.
