### ISSUE TITLE
Feature Request: overwrite file prompt and export profile dropdown

### ISSUE THREAD

**Issue by cityrobo** [EdyJ/blender-to-unity-fbx-exporter#46]
I've noticed that there's not prompt if you want to overwrite a file.
while usually annoying it is a necessary safety feature in my opinion.
it would be good to have because not everybody makes backups.
but it also wouldn't be the first time those prompts have been haphazardly skipped either.

also, a drop down where you can save export profiles for different scenarios like the default exporter has would be appreciated.
while the export options are limited, having a drop down saves just those few clicks.
not entirely necessary but completely awesome to have!

**Comment by EdyJ** [comment]
There's no overwrite prompt in the default FBX Exporter either. Indeed, I can't recall having seen any overwrite file prompt in Blender at all. Blender's file save dialog just shows a red background in the file name when a file with that name already exists and will be overwritten. AFAIK, that's the default behavior in Blender. If that changes in a future Blender version, then the file dialog would include it itself without further action.

With regards to having a profiles option, I agree it would be nice. Not a priority at the moment, but maybe in the future.
