### ISSUE TITLE
Path mode and embedded textures

### ISSUE THREAD

**Issue by mccreery** [EdyJ/blender-to-unity-fbx-exporter#5]
I've been testing out your exporter and it's working great for me in 2.82a. Meshes, armatures and animations seem to export properly. The only problem is textures are not embedded, instead using relative paths.

I would fix this using the standard FBX exporter by setting Path Mode to Copy and the Embed Textures toggle as shown:
![image](https://user-images.githubusercontent.com/4602020/86979252-bed3a880-c178-11ea-938f-23f9f43e33e9.png)

Of the features in the standard exporter, I use this one most often. Do you have any plans to adopt it? Thanks.

**Comment by EdyJ** [comment]
Yes, that should be easy to add.

**Comment by EdyJ** [comment]
I've implemented this feature but textures doesn't seem to get embedded into the FBX. I'm using an example mesh with several materials that use textures, but the FBX file is always written without them even using the default FBX exporter with those options.

Can you provide a simple example .blend file with textures that get embedded into a FBX file using the default exporter?
