### ISSUE TITLE
Maybe not work for blender 4.2?

### ISSUE THREAD

**Issue by kaipard** [EdyJ/blender-to-unity-fbx-exporter#53]
I try to clone it in \xxxx\Blender Foundation\Blender 4.2\4.2\scripts\modules\_bpy_internal\addons, but it does not show in addons in  eit-preference-add-ons。
copy blender-to-unity-fbx-exporter.py does not work either.

**Comment by EdyJ** [comment]
It works correctly on Blender 4.2
![image](https://github.com/user-attachments/assets/09777d7a-a92f-41a4-8cc0-00886c6e43bb)
