### ISSUE TITLE
Blender 2.83.2 - after export script leaves temporary rotations to main scene objects

### ISSUE THREAD

**Issue by piotradev** [EdyJ/blender-to-unity-fbx-exporter#6]
Hi,
I found some kind of bug in the sript. When I Export selected items theirs rotation is incremented by 90 degrees after the script finish. Looks like some temporary rotation problem. The rotations stack up every time You export.
Blender 2.83.2, script 1.2 and 1.2.2

**Comment by EdyJ** [comment]
Can you try if the problem exists in Blender 2.82? I suspect there's some bug related with Undo in Blender 2.83, which may prevent the scene to be restored after exporting.

**Comment by piotradev** [comment]
2.82 was OK. I just switched to 2.83 LTS version and noticed this bug.

czw., 23 lip 2020 o 11:49 EdyJ <notifications@github.com> napisał(a):

**Comment by deradrian** [comment]
Same here, I just update today and yes the rotation remains 90degrees after export on the objects.

**Comment by piotradev** [comment]
Tested 2.9 and there is the same situation. Is there any chance to fix the temporary rotation bug?

**Comment by EdyJ** [comment]
The addon tries to save the Undo state before modifying the objects, then restore it afterwards. How to use the Undo API is not well documented. This trick worked with Blender 2.81, but something seems to have changed internally and it doesn't work anymore. 

Does pressing Undo (Ctrl-Z) after exporting fixes the scene? Maybe pressing Ctrl-Z several times? I haven't yet upgraded from 2.81, but I'm just trying to figure out possible solutions for fixing the addon.

**Comment by deradrian** [comment]
Sometimes Control+Z works sometimes no, in my case I just revert the scene after export.

**Comment by EdyJ** [comment]
I could make the addon save & revert the entire file, but I'm trying to avoid saving the file without user's consent. Sometimes you may want to export some temporary change without saving the file.

**Comment by deradrian** [comment]
Yup, not really a good option.

**Comment by piotradev** [comment]
Ctrl-Z makes objects rotate and is not going back to the original state like before export.
Maybe we could use optional checkbox "save&restore" just like the "export only selected".
I am so happy to use this script and wonder why not push this "Unity export" to the original code developers?

**Comment by EdyJ** [comment]
It had to do with how the exporter handled undo. This is mostly undocumented, but I've finally found a way where undo works properly.
