### ISSUE TITLE
Blender 2.83, error when trying to export sometimes (may be linked to export the same file more than 2 times)

### ISSUE THREAD

**Issue by 990xan** [EdyJ/blender-to-unity-fbx-exporter#7]
https://hatebin.com/rpektbnddk

**Comment by EdyJ** [comment]
I'd need a repro file and a procedure to reproduce the issue as consistently as possible.

**Comment by EdyJ** [comment]
I've fixed how Undo is managed internally by the plugin, so this might be resolved as well (maybe undo left the scene in some undefined state)
