### ISSUE TITLE
Blender 2.90 / 2.83 - Doesn't show up in addons list

### ISSUE THREAD

**Issue by GlobalHive** [EdyJ/blender-to-unity-fbx-exporter#9]
I tryed to install the addon as described on the front page, the console tells me it has been installed.
It got copyed indeed but i can't activate it, since its not showing up inside blender in the add-ons tab

**Comment by EdyJ** [comment]
I've just tested both 2.83 and 2.90 and the add-on shows properly in the list, can be activated and works properly. I'd recommend you to reset your Blender setup and try again.

**Comment by enquel** [comment]
Same here. B 2.92 Beta

**Comment by MaximillianCat** [comment]
This was a simple issue of not paying close attention to what file I was actually trying to install, combined with Blender not actually throwing any errors to explain why it wasn't adding the plugin.  I can see how general users might make this mistake.

Long story short, thank you for this very useful plugin, and reading my attempts to solve the issue.

**Comment by EdyJ** [comment]
For the record, at the time of writing this I'm using the plugin in Blender 2.92 and the release notes for 2.93 don't report any compatibility-breaking changes in the Python API.
